tolerate missing node.kind
problem is
```
astring.js:818
    if (node.method || node.kind[0] !== 'i') {
TypeError: Cannot read property '0' of undefined
```

this happens when i run
```
const lave = require('lave')
const astring = require('astring')
console.log('astr = '+astring.generate(lave({a: 1})))
```
lave = eval in reverse = get ast of a live object = https://github.com/jed/lave

with the proposed change, result is as expected
```
astr = ({
  "a": 1
});
```